package pojos;
// Generated Jun 24, 2019 5:26:02 AM by Hibernate Tools 4.3.1



/**
 * Actor1 generated by hbm2java
 */
public class Actor1  implements java.io.Serializable {


     private int actorid;
     private String firstName;
     private String lastName;

    public Actor1() {
    }

	
    public Actor1(int actorid) {
        this.actorid = actorid;
    }
    public Actor1(int actorid, String firstName, String lastName) {
       this.actorid = actorid;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getActorid() {
        return this.actorid;
    }
    
    public void setActorid(int actorid) {
        this.actorid = actorid;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


